name: Daily Guess-The-Team
on:
  schedule:
    - cron: "10 12 * * *"   # ~08:10 ET
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install "Pillow<10" "moviepy==1.0.3" imageio-ffmpeg google-api-python-client google-auth

      - name: Fetch flags & build college placeholders
        run: python fetch_assets.py

      - name: Render three Shorts
        run: |
          python render_guess_team.py data/lineup_basketball.json
          python render_guess_team.py data/lineup_football.json
          python render_guess_team.py data/lineup_soccer.json


      - name: Upload 3 Shorts (staggered)
        env:
          YT_TOKEN_JSON_BASE64: ${{ secrets.YT_TOKEN_JSON_BASE64 }}
        run: |
          set -e
          for JSON in data/lineup_basketball.json data/lineup_football.json data/lineup_soccer.json; do
            MP4="${JSON%.json}_guess_team.mp4"
            TITLE=$(python -c "import json,sys; d=json.load(open(sys.argv[1])); print((d.get('title','Guess The Team')) + ' (' + str(d.get('year','')) + ')')" "$JSON")
            DESC="Daily Guess-The-Team challenge. Can you name the squad? #Shorts #Sports #Trivia"
            TAGS="sports,trivia,shorts"

            echo "Uploading: $MP4 -> $TITLE"
            python upload_youtube.py "$MP4" "$TITLE" "$DESC" "$TAGS"

            # Stagger next upload 15–35 minutes to avoid spam signals
            if [ "$JSON" != "data/lineup_soccer.json" ]; then
              delay=$(( (RANDOM % 20 + 15) * 60 ))
              echo "Sleeping $delay seconds before next upload…"
              sleep $delay
            fi
          done

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: daily guess-the-team" || echo "No changes"
          git push
