name: Daily Guess-The-Team

on:
  schedule:
    - cron: "10 12 * * *"   # runs daily at 12:10 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # System tools for video
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # ⬇️ Install Python libs (moviepy, Pillow, requests, etc.)
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install "Pillow<10" "moviepy==1.0.3" imageio-ffmpeg google-api-python-client google-auth requests

      # ⬇️ ADD THIS BEFORE RENDERING: fetch logos/flags into assets/
      - name: Fetch logos & flags (on-demand, with manifest)
        run: |
          python fetch_assets_v4.py data/lineup_basketball.json data/lineup_football.json data/lineup_soccer.json

      # ⬇️ Now render (these steps come AFTER the fetch step)
      - name: Render three Shorts
        run: |
          python render_guess_team.py data/lineup_basketball.json
          python render_guess_team.py data/lineup_football.json
          python render_guess_team.py data/lineup_soccer.json

      # (Optional) commit outputs
      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: daily guess-the-team" || echo "No changes"
          git push
